on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    paths:
    - .github/workflows/semgrep.yml
name: Semgrep
jobs:
  my_first_job: 
    name: PipfileLockGeneration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Pipfile.lock
        run: |
          pip install pipenv --user
          pipenv lock
      - name: Upload Requirements File as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pipfilelock
          path: Pipfile.lock
  my_second_job:
    needs: my_first_job
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact from previous job
        uses: actions/download-artifact@v3
        with:
          name: pipfilelock
      - run: semgrep ci --supply-chain --verbose --exclude requirements.txt
